- id: xmllint-format
  name: xmllint-format
  description: Lint xml files with xmllint
  entry: /run.sh
  language: docker
  types: [xml]
  args:
    - --recover # Output any parsable portions of an invalid document.
    - --format # Reformat and reindent the output.
    - --noblanks # Drop ignorable blank spaces.
    - --nsclean # Remove redundant namespace declarations.
    - --XMLLINT_INDENT # Use a specific indentation string (normally this is an env var)
    - "    " # Indentation string to use

